require_modules(
	'ceremony/object/enums',
	'ceremony/object/equip',
	'ceremony/object/soldier',
	'ceremony/object/role',
	'ceremony/object/role_card',
	'ceremony/object/gem',
	'ceremony/object/material',
	'ceremony/object/pawn'
)