require_modules(
	'ceremony/awake/roleawake',
	'ceremony/awake/enums',
	'ceremony/awake/awake_guanyu',
	'ceremony/awake/awake_luoshen',
	'ceremony/awake/awake_zhugeliang',
	'ceremony/awake/awake_lvbu',
	'ceremony/awake/awake_zhaoyun',
	'ceremony/awake/awake_zuoci',
	'ceremony/awake/awake_huatuo',
	'ceremony/awake/awake_tongyuan'
)