LegionHelpPanel = LegionView:new{
	jsonFile = 'panel/legion_help_panel.json',
	panelName = 'legion-help-panel'
}

function LegionHelpPanel:init()
	self.panel:setAdaptInfo('help_bg_img', 'help_img')
	self.panel:registerInitHandler(function()
		local root = self.panel:GetRawPanel()
		self:registerButtonWithHandler(root, 'close_btn', BUTTON_SOUND_TYPE.CLOSE_EFFECT, function()
			LegionController.close(self, ELF_HIDE.ZOOM_OUT_FADE_OUT)
		end)
		self:registerButtonWithHandler(root, 'help_bg_img', nil, function()
			LegionController.close(self, ELF_HIDE.ZOOM_OUT_FADE_OUT)
		end)

		local sv = tolua.cast(root:getChildByName('system_sv'), 'UIScrollView')
		local title1 = tolua.cast(sv:getChildByName('title_1_tx'), 'UILabel')
		title1:setPreferredSize(580,1)
		local title2 = tolua.cast(sv:getChildByName('title_2_tx'), 'UILabel')
		title2:setPreferredSize(580,1)
		local title3 = tolua.cast(sv:getChildByName('title_3_tx'), 'UILabel')
		title3:setPreferredSize(580,1)
		local title4 = tolua.cast(sv:getChildByName('title_4_tx'), 'UILabel')
		title4:setPreferredSize(580,1)
		local infoTx1 = tolua.cast(sv:getChildByName('info_1_tx'), 'UILabel')
		infoTx1:setText(getLocalStringValue('HELP_LEGION_1'))
		infoTx1:setPreferredSize(580,1)
		local infoTx2 = tolua.cast(sv:getChildByName('info_2_tx'), 'UILabel')
		infoTx2:setText(getLocalStringValue('HELP_LEGION_2'))
		infoTx2:setPreferredSize(580,1)
		local infoTx3 = tolua.cast(sv:getChildByName('info_3_tx'), 'UILabel')
		infoTx3:setText(getLocalStringValue('HELP_LEGION_3'))
		infoTx3:setPreferredSize(580,1)
		local infoTx4 = tolua.cast(sv:getChildByName('info_4_tx'), 'UILabel')
		infoTx4:setText(getLocalStringValue('HELP_LEGION_4'))
		infoTx4:setPreferredSize(580,1)	
		local infoTx5 = tolua.cast(sv:getChildByName('info_5_tx'), 'UILabel')
		infoTx5:setText(getLocalStringValue('HELP_LEGION_5'))
		infoTx5:setPreferredSize(580,1)
		local infoTx6 = tolua.cast(sv:getChildByName('info_6_tx'), 'UILabel')
		infoTx6:setText(getLocalStringValue('HELP_LEGION_6'))
		infoTx6:setPreferredSize(580,1)	
		local infoTx7 = tolua.cast(sv:getChildByName('info_7_tx'), 'UILabel')
		infoTx7:setText(getLocalStringValue('HELP_LEGION_7'))
		infoTx7:setPreferredSize(580,1)	
		local infoTx8 = tolua.cast(sv:getChildByName('info_8_tx'), 'UILabel')
		infoTx8:setText(getLocalStringValue('HELP_LEGION_8'))
		infoTx8:setPreferredSize(580,1)	
		local infoTx9 = tolua.cast(sv:getChildByName('info_9_tx'), 'UILabel')
		infoTx9:setText(getLocalStringValue('HELP_LEGION_9'))
		infoTx9:setPreferredSize(580,1)	
		local infoTx10 = tolua.cast(sv:getChildByName('info_10_tx'), 'UILabel')
		infoTx10:setText(getLocalStringValue('HELP_LEGION_10'))
		infoTx10:setPreferredSize(580,1)	
		local infoTx11 = tolua.cast(sv:getChildByName('info_11_tx'), 'UILabel')
		infoTx11:setText(getLocalStringValue('HELP_LEGION_11'))
		infoTx11:setPreferredSize(580,1)	
		local infoTx12 = tolua.cast(sv:getChildByName('info_12_tx'), 'UILabel')
		infoTx12:setText(getLocalStringValue('HELP_LEGION_12'))
		infoTx12:setPreferredSize(580,1)	
		local infoTx13 = tolua.cast(sv:getChildByName('info_13_tx'), 'UILabel')
		infoTx13:setText(getLocalStringValue('HELP_LEGION_13'))
		infoTx13:setPreferredSize(580,1)	
		local infoTx14 = tolua.cast(sv:getChildByName('info_14_tx'), 'UILabel')
		infoTx14:setText(getLocalStringValue('HELP_LEGION_14'))
		infoTx14:setPreferredSize(580,1)	
		sv:setClippingEnable(true)
		sv:scrollToTop()
	end)
end