require_modules(
	'ceremony/panel/enums',
	'ceremony/panel/summerdays',
	'ceremony/panel/lucky_card',
	--'ceremony/panel/new_sign_in',
	'ceremony/panel/challenge_tower',
	'ceremony/panel/protection',
	'ceremony/panel/card_master',
	'ceremony/panel/destiny_wheel',
	'ceremony/panel/pawn_shop',
	'ceremony/panel/buy_panel',
	'ceremony/panel/award_panel',
	'ceremony/panel/worldboss/worldboss_panel',
	'ceremony/panel/worldboss/worldboss_rank',
	'ceremony/panel/worldboss/worldboss_award',
	'ceremony/panel/worldboss/worldboss_battle_panel',
	'ceremony/panel/worldboss/worldboss_hurtreward_panel',
	'ceremony/panel/worldboss/worldboss_challenge_help_panel',
	'ceremony/panel/worldboss/worldboss_reward_help_panel',
	'ceremony/panel/worldboss/worldboss_controller',
	'ceremony/panel/one_ride_panel',
	'ceremony/panel/accumulatepay_panel',
	'ceremony/panel/national_day_panel',
	'ceremony/panel/grave_panel',
	'ceremony/panel/welfare_panel',
	'ceremony/panel/welfare_panel1',
	'ceremony/panel/luck_runner_panel',
	'ceremony/panel/thxgiving_panel',
	'ceremony/panel/new_give_god_award',
	'ceremony/panel/new_give_god',
	'ceremony/panel/hofman',
	'ceremony/panel/arena_choice_panel',
	'ceremony/panel/shop_main_panel',
	'ceremony/panel/shop_tegou_panel',
	'ceremony/panel/shop_tuangou_panel',
	'ceremony/panel/shop_miaosha_panel',
	'ceremony/panel/shop_heidian_panel',
	'ceremony/panel/shop_shengwang_panel',
	'ceremony/panel/recharge_panel',
	'ceremony/panel/hofman',
	'ceremony/panel/ob_zh_get_awards',
	'ceremony/panel/friends_card_panel',
	'ceremony/panel/friends_panel',
	'ceremony/panel/friends_recommend_panel',
	'ceremony/panel/check_role_panel',
	'ceremony/panel/avfood',
	'ceremony/panel/avpay',
	-- 'ceremony/panel/altar',
	'ceremony/panel/avborrowarrow_new',
	'ceremony/panel/avluckyroll',
	'ceremony/panel/chat/chat_data',
	'ceremony/panel/garrison_main_panel',
	'ceremony/panel/garrison_mine_panel',
	'ceremony/panel/garrison_select_role_panel',
	'ceremony/panel/garrison_time_panel',
	'ceremony/panel/rechangereb_panel',
	'ceremony/panel/rankgifs_panel',
	'ceremony/panel/help/rechangereb_help',
	-- 'ceremony/launchers/getotherfightforce',
	'ceremony/panel/shop_discount_panel',
	'ceremony/panel/lvup_panel'
	-- 'ceremony/panel/fragment',
	-- 'ceremony/panel/blacksmith/blacksmith_manager',
	-- 'ceremony/panel/blacksmith/blacksmith_data',
	-- 'ceremony/panel/combine',
	-- 'ceremony/panel/role_soul_goto',
	-- 'ceremony/panel/rolefate/all'
)
