local function genViewUpdater(panel, help)
	return function() 
		local root = panel:GetRawPanel()
        local helpBgImg = tolua.cast(root:getChildByName('trena_bg_img'), 'UIImageView')
        local helpImg = tolua.cast(helpBgImg:getChildByName('trena_img'), 'UIImageView')
        local closeBtn = tolua.cast(helpImg:getChildByName('close_btn'), 'UIButton')
        GameController.addButtonSound(closeBtn, BUTTON_SOUND_TYPE.CLOSE_EFFECT)
		closeBtn:registerScriptTapHandler(function()
			CUIManager:GetInstance():HideObject(help, ELF_HIDE.SMART_HIDE)
		end)

		local knowBtn = tolua.cast(helpImg:getChildByName('know_btn'), 'UITextButton')
        GameController.addButtonSound(knowBtn, BUTTON_SOUND_TYPE.CLOSE_EFFECT)
		knowBtn:registerScriptTapHandler(function()
			CUIManager:GetInstance():HideObject(help, ELF_HIDE.SMART_HIDE)
		end)
		local helpSv = tolua.cast(helpImg:getChildByName('help_sv'),'UIScrollView')
		helpSv:setClippingEnable(true)
		helpSv:scrollToTop()

		local infoTx1 = tolua.cast(helpImg:getChildByName('info_1_tx'), 'UILabel')
		infoTx1:setText(getLocalStringValue('HELP_TRENA_1'))
		infoTx1:setPreferredSize(600,1)
		local infoTx2 = tolua.cast(helpImg:getChildByName('info_2_tx'), 'UILabel')
		infoTx2:setText(getLocalStringValue('HELP_TRENA_2'))
		infoTx2:setPreferredSize(600,1)
		local infoTx3 = tolua.cast(helpImg:getChildByName('info_3_tx'), 'UILabel')
		infoTx3:setText(getLocalStringValue('HELP_TRENA_3'))
		infoTx3:setPreferredSize(600,1)
		local infoTx4 = tolua.cast(helpImg:getChildByName('info_4_tx'), 'UILabel')
		infoTx4:setText(getLocalStringValue('HELP_TRENA_4'))
		infoTx4:setPreferredSize(600,1)
		local infoTx5 = tolua.cast(helpImg:getChildByName('info_5_tx'), 'UILabel')
		infoTx5:setText(getLocalStringValue('HELP_TRENA_5'))
		infoTx5:setPreferredSize(600,1)
		local infoTx6 = tolua.cast(helpImg:getChildByName('info_6_tx'), 'UILabel')
		infoTx6:setText(getLocalStringValue('HELP_TRENA_6'))
		infoTx6:setPreferredSize(600,1)
		local infoTx7 = tolua.cast(helpImg:getChildByName('info_7_tx'), 'UILabel')
		infoTx7:setText(getLocalStringValue('HELP_TRENA_7'))
		infoTx7:setPreferredSize(600,1)
		local infoTx8 = tolua.cast(helpImg:getChildByName('info_8_tx'), 'UILabel')
		infoTx8:setText(getLocalStringValue('HELP_TRENA_8'))
		infoTx8:setPreferredSize(600,1)		
	end
end

function genTrenaHelpPanel()
    local help = SceneObjEx:createObj('panel/trena_help_panel.json', 'trena-help-lua')

    local panel = help:getPanelObj()        --# This is a BasePanelEx object
    panel:setAdaptInfo('trena_bg_img', 'trena_img')
    local viewUpdater = genViewUpdater(panel, help)

	panel:registerInitHandler(function()
		viewUpdater()
	end)
    -- Show now
    CUIManager:GetInstance():ShowObject(help, ELF_SHOW.SMART)
end
